services:
  pocketbase:
    image: ghcr.io/pocketbase/pocketbase:0.25.4
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_public:/pb/pb_public
      - ./pb_migrations:/pb/pb_migrations
    command: serve --http=0.0.0.0:8090 --dir /pb/pb_data --publicDir /pb/pb_public --migrationsDir /pb/pb_migrations
